version: '3'

services:
  ros_melodic:
    build: .
    entrypoint: /ros_entrypoint.sh roscore

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1  #fix some QT bugs
    volumes:
      #for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix
      #access device at host
      - /dev:/dev
      #workspace
      - ./ws:/root/ws

    working_dir: /root/ws


    #--privileged
    privileged: true
    
    #--runtime=nvidia
    runtime: nvidia
    
    #--net=host
    network_mode: host